on_error: Use curly braces
This should also improve compiler error messages because now only the
head of the if condition is a macro, not the entire thing.